name: Deploy Lovable via FTP na Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências ignorando conflitos
        run: npm install --legacy-peer-deps

      - name: Build do projeto
        run: npm run build

      - name: Criar .htaccess para SPA
        run: |
          echo "<IfModule mod_rewrite.c>" > dist/.htaccess
          echo "  RewriteEngine On" >> dist/.htaccess
          echo "  RewriteBase /" >> dist/.htaccess
          echo "  RewriteRule ^index\.html$ - [L]" >> dist/.htaccess
          echo "  RewriteCond %{REQUEST_FILENAME} !-f" >> dist/.htaccess
          echo "  RewriteCond %{REQUEST_FILENAME} !-d" >> dist/.htaccess
          echo "  RewriteRule . /index.html [L]" >> dist/.htaccess
          echo "</IfModule>" >> dist/.htaccess

      - name: Mostrar arquivos gerados
        run: ls -al dist/

      - name: Deploy FTP para Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: dist/
          server-dir: /
          dangerous-clean-slate: true
          dry-run: false
          log-level: verbose
